package com.omnibuscode.ctrl;

public class ClovaServletTest {

    public String getResJsonSucc00() {
        StringBuffer resJsonSb = new StringBuffer();

        // 뭔지 모르지만 실패!!
//        resJsonSb.append("{");
//        resJsonSb.append("  \"type\": \"Popup\",");
//        resJsonSb.append("  \"displayType\": \"POPUP\",");
//        resJsonSb.append("  \"toastText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"toastLinkText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"toastLinkUrl\": {");
//        resJsonSb.append("    \"type\": \"url\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"alertText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"title\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"취향파악 완료!\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"mainText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"이제 뮤직 100곡 무료 이용권으로 클로바의 추천 음악을 즐기세요!\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"negativeButtonText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"negativeButtonUrl\": {");
//        resJsonSb.append("    \"type\": \"url\",");
//        resJsonSb.append("    \"value\": \"\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"positiveButtonText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"뮤직 이용권 받기\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"positiveButtonUrl\": {");
//        resJsonSb.append("    \"type\": \"url\",");
//        resJsonSb.append("    \"value\": \"https://www.naver.com\"");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // NOT YET
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {");
//        resJsonSb.append("      \"type\": \"SpeechList\",");
//        resJsonSb.append("      \"values\": ");
//        resJsonSb.append("        {");
//        resJsonSb.append("          \"type\": \"PlainText\",");
//        resJsonSb.append("          \"lang\": \"ko\",");
//        resJsonSb.append("          \"value\": \"노래를 불러볼게요.\"");
//        resJsonSb.append("        }");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"card\": "+resJsonSb.toString()+",");
//        resJsonSb.append("    \"directives\": [],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // card 출력 안됨(음성 출력 OK)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {},");
//        resJsonSb.append("    \"card\": "+resJsonSb.toString()+",");
//        resJsonSb.append("    \"directives\": [");
//        resJsonSb.append("      {");
//        resJsonSb.append("        \"header\": {");
//        resJsonSb.append("          \"namespace\": \"Clova\",");
//        resJsonSb.append("          \"name\": \"ExpectLogin\"");
//        resJsonSb.append("        },");
//        resJsonSb.append("        \"payload\": {");
//        resJsonSb.append("          \"guideInfo\": {");
//        resJsonSb.append("            \"useDefault\": \"false\",");
//        resJsonSb.append("            \"message\": \"로그인이 필요한 서비스입니다. 로그인해주세요.\"");
//        resJsonSb.append("          }");
//        resJsonSb.append("        }");
//        resJsonSb.append("      }");
//        resJsonSb.append("    ],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // 카드 출력 안됨 (실패)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {");
//        resJsonSb.append("      \"type\": \"SimpleSpeech\",");
//        resJsonSb.append("      \"values\": {");
//        resJsonSb.append("        \"type\": \"PlainText\",");
//        resJsonSb.append("        \"lang\": \"ko\",");
//        resJsonSb.append("        \"value\": \"버튼을 눌러주세요.\"");
//        resJsonSb.append("      }");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"card\": {");
//        resJsonSb.append("      \"type\": \"ButtonsTemplate\",");
//        resJsonSb.append("      \"buttons\": [");
//        resJsonSb.append("        {");
//        resJsonSb.append("          \"type\": \"webLinkUrl\",");
//        resJsonSb.append("          \"url\": \"https://example.com\",");
//        resJsonSb.append("          \"title\": \"웹사이트 방문\"");
//        resJsonSb.append("        }");
//        resJsonSb.append("      ]");
//        resJsonSb.append("    }");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

//        //card 출력 안됨 (실패)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {},");
//        resJsonSb.append("    \"card\": ");
//
//        resJsonSb.append("{");
//        resJsonSb.append("  \"type\": \"Popup\",");
//        resJsonSb.append("  \"displayType\": \"TOAST\",");
//        resJsonSb.append("  \"toastText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"토스트 테스트입니다. 로그인하세요!\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"toastLinkText\": {");
//        resJsonSb.append("    \"type\": \"string\",");
//        resJsonSb.append("    \"value\": \"로그인 >\"");
//        resJsonSb.append("  },");
//        resJsonSb.append("  \"toastLinkUrl\": {");
//        resJsonSb.append("    \"type\": \"url\",");
//        resJsonSb.append("    \"value\": \"https://www.naver.com\"");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");
//
//        resJsonSb.append("    ,");
//        resJsonSb.append("    \"directives\": [],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // card 출력 안됨 (실패)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {");
//        resJsonSb.append("      \"type\": \"SimpleSpeech\",");
//        resJsonSb.append("      \"lang\": \"ko\",");
//        resJsonSb.append("      \"value\": \"오늘 날씨 정보입니다.\"");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"card\": {");
//        resJsonSb.append("      \"type\": \"Popup\",");
//        resJsonSb.append("      \"title\": \"오늘 날씨\",");
//        resJsonSb.append("      \"content\": {");
//        resJsonSb.append("        \"type\": \"Image\",");
//        resJsonSb.append("        \"url\": \"https://example.com/weather.png\",");
//        resJsonSb.append("        \"width\": 400,");
//        resJsonSb.append("        \"height\": 300");
//        resJsonSb.append("      },");
//        resJsonSb.append("      \"buttons\": [");
//        resJsonSb.append("        {");
//        resJsonSb.append("          \"type\": \"TextButton\",");
//        resJsonSb.append("          \"title\": \"자세히 보기\",");
//        resJsonSb.append("          \"onClick\": {");
//        resJsonSb.append("            \"type\": \"OpenUri\",");
//        resJsonSb.append("            \"uri\": \"https://example.com/weather\"");
//        resJsonSb.append("          }");
//        resJsonSb.append("        }");
//        resJsonSb.append("      ]");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"directives\": [],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // card 출력 안됨 (실패)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {");
//        resJsonSb.append("      \"type\": \"SpeechSet\",");
//        resJsonSb.append("      \"brief\": {");
//        resJsonSb.append("        \"type\": \"PlainText\",");
//        resJsonSb.append("        \"lang\": \"ko\",");
//        resJsonSb.append("        \"value\": \"날씨 뉴스 입니다.\"");
//        resJsonSb.append("      },");
//        resJsonSb.append("      \"verbose\": {");
//        resJsonSb.append("        \"type\": \"SpeechList\",");
//        resJsonSb.append("        \"values\": [");
//        resJsonSb.append("          {");
//        resJsonSb.append("              \"type\": \"PlainText\",");
//        resJsonSb.append("              \"lang\": \"ko\",");
//        resJsonSb.append("              \"value\": \"주말까지 전국 장맛비…폭염 누그러져.\"");
//        resJsonSb.append("          },");
//        resJsonSb.append("          {");
//        resJsonSb.append("              \"type\": \"PlainText\",");
//        resJsonSb.append("              \"lang\": \"ko\",");
//        resJsonSb.append("              \"value\": \"내일 전국 장맛비…곳곳 국지성 호우 주의.\"");
//        resJsonSb.append("          }");
//        resJsonSb.append("        ]");
//        resJsonSb.append("      }");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"card\": {},");
//        resJsonSb.append("    \"directives\": [],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // URL 출력 (url을 디바이스에 전달하여 플레이 하게함, 오류는 없지만 정상 동작 확인 못함)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"0.1.0\",");
//        resJsonSb.append("  \"sessionAttributes\": {},");
//        resJsonSb.append("  \"response\": {");
//        resJsonSb.append("    \"outputSpeech\": {");
//        resJsonSb.append("      \"type\": \"SpeechList\",");
//        resJsonSb.append("      \"values\": [");
//        resJsonSb.append("        {");
//        resJsonSb.append("          \"type\": \"PlainText\",");
//        resJsonSb.append("          \"lang\": \"ko\",");
//        resJsonSb.append("          \"value\": \"노래를 불러볼게요.\"");
//        resJsonSb.append("        },");
//        resJsonSb.append("        {");
//        resJsonSb.append("          \"type\": \"URL\",");
//        resJsonSb.append("          \"lang\": \"\" ,");
//        resJsonSb.append("          \"value\": \"https://tts.example.com/song.mp3\"");
//        resJsonSb.append("        }");
//        resJsonSb.append("      ]");
//        resJsonSb.append("    },");
//        resJsonSb.append("    \"card\": {},");
//        resJsonSb.append("    \"directives\": [],");
//        resJsonSb.append("    \"shouldEndSession\": true");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // URL 오픈 테스트 (실패)
//        resJsonSb.append("{");
//        resJsonSb.append("  \"version\": \"2.0\",");
//        resJsonSb.append("  \"template\": {");
//        resJsonSb.append("    \"outputs\": [");
//        resJsonSb.append("      {");
//        resJsonSb.append("        \"simpleText\": {");
//        resJsonSb.append("          \"text\": \"링크를 클릭하여 웹페이지를 확인해 주세요.\"");
//        resJsonSb.append("        }");
//        resJsonSb.append("      }");
//        resJsonSb.append("    ],");
//        resJsonSb.append("    \"quickReplies\": [");
//        resJsonSb.append("      {");
//        resJsonSb.append("        \"messageText\": \"웹페이지 열기\",");
//        resJsonSb.append("        \"action\": \"block\",");
//        resJsonSb.append("        \"blockId\": \"your_block_id\",");
//        resJsonSb.append("        \"label\": \"웹페이지 열기\",");
//        resJsonSb.append("        \"extra\": {");
//        resJsonSb.append("          \"url\": \"https://example.com\"");
//        resJsonSb.append("        }");
//        resJsonSb.append("      }");
//        resJsonSb.append("    ]");
//        resJsonSb.append("  }");
//        resJsonSb.append("}");

        // response.card 이용 (성공)
        // https://developers.naver.com/console/clova/custom_ext/Develop/Guides/Build_Custom_Extension.md#ReturnCustomExtensionResponse
        resJsonSb.append("{");
        resJsonSb.append("  \"version\": \"0.1.0\",");
        resJsonSb.append("  \"sessionAttributes\": {},");
        resJsonSb.append("  \"response\": {");
        resJsonSb.append("    \"outputSpeech\": {");
        resJsonSb.append("      \"type\": \"SimpleSpeech\",");
        resJsonSb.append("      \"values\": {");
        resJsonSb.append("          \"type\": \"PlainText\",");
        resJsonSb.append("          \"lang\": \"ko\",");
        resJsonSb.append("          \"value\": \"리오넬 메시의 사진이에요.\"");
        resJsonSb.append("      }");
        resJsonSb.append("    },");
        resJsonSb.append("    \"card\": {");
        resJsonSb.append("      \"type\": \"ImageText\",");
        resJsonSb.append("      \"imageUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"mainText\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"리오넬 메시\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceText\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"검색결과\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append(
                "        \"value\": \"https://m.search.example.com/search.naver?where=m&sm=mob_lic&query=%eb%a6%ac%ec%98%a4%eb%84%ac+%eb%a9%94%ec%8b%9c+%ec%86%8c%ec%86%8d%ed%8c%80\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"subTextList\": [");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"FC 바르셀로나\"");
        resJsonSb.append("        }");
        resJsonSb.append("      ],");
        resJsonSb.append("      \"thumbImageType\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"인물\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"thumbImageUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"https://sstatic.example.net/people/3/201607071816066361.jpg\"");
        resJsonSb.append("      }");
        resJsonSb.append("    },");
        resJsonSb.append("    \"directives\": [],");
        resJsonSb.append("    \"shouldEndSession\": true");
        resJsonSb.append("  }");
        resJsonSb.append("}");

        return resJsonSb.toString();
    }
    
    public String getResJsonSucc01() {
        StringBuffer resJsonSb = new StringBuffer();
        
        resJsonSb.append("{");
        resJsonSb.append("  \"subType\": \"Type4\",");
        resJsonSb.append("  \"type\": \"CardList\",");
        resJsonSb.append("  \"noticeText\": {");
        resJsonSb.append("    \"type\": \"string\",");
        resJsonSb.append("    \"value\": \"자동 추출 기술로 요약된 내용으로, 본문의 주요 내용이 제외될 수 있습니다.\"");
        resJsonSb.append("  },");
        resJsonSb.append("  \"cardList\": [");
        resJsonSb.append("    {");
        resJsonSb.append("      \"contentProviderText\" : {");
        resJsonSb.append("        \"type\" : \"string\",");
        resJsonSb.append("        \"value\" : \"뉴스\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"description\": [");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"다음 달이면 말 많고 탈 많았던 '4대강'의 보 수문이 열립니다. 문재인 대통령이 지난 22일 '4대강 사업'에 대한 감사 지시를 하면서 이뤄진 결정입니다. 이를 계기로 4대강 사업 논란이 다시 수면 위로 떠올랐습니\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"\"");
        resJsonSb.append("        }");
        resJsonSb.append("      ],");
        resJsonSb.append("      \"imageUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"linkUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"https://news.contentservice.example.com/main/read.nhn?mode=LSD&mid=sec&sid1=001&oid=025&aid=0002720454\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"press\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"중앙일보\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"publishDate\": {");
        resJsonSb.append("        \"type\": \"date\",");
        resJsonSb.append("        \"value\": \"2017-05-28\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceText\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"title\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"[시민마이크]'녹차라떼 4대강' 감사, 시민들의 생각은?\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"videoUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      }");
        resJsonSb.append("    },");
        resJsonSb.append("    {");
        resJsonSb.append("      \"contentProviderText\" : {");
        resJsonSb.append("        \"type\" : \"string\",");
        resJsonSb.append("        \"value\" : \"뉴스\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"description\": [");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"5월 마지막 주말 나들이객 줄이어더위 식히고 모래작품 보고(부산=연합뉴스) 조정호 기자 = 초여름 날씨를 보인 28일 부산 해운대 모래축제가 열린 해운대해수욕장에서 나들이객들이 가로 25ｍ, 높이 5ｍ 크기의 대형 모래작품을 구경하고 있습니다. 2017.5.28(전국종합=연합뉴스) 5월의 마지막 주말인 28일 초여름 날씨가...\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"\"");
        resJsonSb.append("        }");
        resJsonSb.append("      ],");
        resJsonSb.append("      \"imageUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"linkUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"https://news.contentservice.example.com/main/read.nhn?mode=LSD&mid=sec&sid1=001&oid=001&aid=0009297247\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"press\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"연합뉴스\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"publishDate\": {");
        resJsonSb.append("        \"type\": \"date\",");
        resJsonSb.append("        \"value\": \"2017-05-28\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceText\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"referenceUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"title\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"단오제 등 전국 곳곳 축제…초여름 날씨에 때이른 피서 행렬\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"videoUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"\"");
        resJsonSb.append("      }");
        resJsonSb.append("    }");
        resJsonSb.append("  ]");
        resJsonSb.append("}");
        
        return resJsonSb.toString();
    }
    
    public String getResJsonSucc02() {
        StringBuffer resJsonSb = new StringBuffer();
        
        resJsonSb.append("{");
        resJsonSb.append("  \"subType\": \"Type4\",");
        resJsonSb.append("  \"type\": \"CardList\",");
        resJsonSb.append("  \"noticeText\": {");
        resJsonSb.append("    \"type\": \"string\",");
        resJsonSb.append("    \"value\": \"각 보관함을 조회한 결과입니다.\"");
        resJsonSb.append("  },");
        resJsonSb.append("  \"cardList\": [");
        resJsonSb.append("    {");
        resJsonSb.append("      \"contentProviderText\" : {");
        resJsonSb.append("        \"type\" : \"string\",");
        resJsonSb.append("        \"value\" : \"지니박스\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"title\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"1BOX\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"description\": [");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템00\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템01\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템02\"");
        resJsonSb.append("        }");
        resJsonSb.append("      ],");
        resJsonSb.append("      \"linkUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"https://dev.jiniebox.com/jbs/box_info.jsp?seq_box=3\"");
        resJsonSb.append("      }");
        resJsonSb.append("    },");
        resJsonSb.append("    {");
        resJsonSb.append("      \"contentProviderText\" : {");
        resJsonSb.append("        \"type\" : \"string\",");
        resJsonSb.append("        \"value\" : \"지니박스\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"title\": {");
        resJsonSb.append("        \"type\": \"string\",");
        resJsonSb.append("        \"value\": \"2BOX\"");
        resJsonSb.append("      },");
        resJsonSb.append("      \"description\": [");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템10\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템11\"");
        resJsonSb.append("        },");
        resJsonSb.append("        {");
        resJsonSb.append("          \"type\": \"string\",");
        resJsonSb.append("          \"value\": \"아이템12\"");
        resJsonSb.append("        }");
        resJsonSb.append("      ],");
        resJsonSb.append("      \"linkUrl\": {");
        resJsonSb.append("        \"type\": \"url\",");
        resJsonSb.append("        \"value\": \"https://dev.jiniebox.com/jbs/box_info.jsp?seq_box=4\"");
        resJsonSb.append("      }");
        resJsonSb.append("    },");
        resJsonSb.append("  ]");
        resJsonSb.append("}");
        
        return resJsonSb.toString();
    }
}
